/**
 * Brand photo pipeline.
 *
 *   npm run images
 *
 * Reads the owner's photos from brand-assets/{logo,cover,owner,team,store,visits,products,testimonials},
 * and for each one:
 *   - auto-orients from EXIF, then strips ALL metadata (EXIF, GPS location, camera serials)
 *   - resizes to responsive widths (never upscales)
 *   - exports AVIF + WebP to public/images/<folder>/<name>-<width>.<ext>
 *   - makes a tiny blurred placeholder (base64 data URL)
 * Then writes the typed manifest src/content/images.ts and lists empty folders
 * in TODO.md between the "missing-photos" markers.
 */
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC = "brand-assets";
const OUT = "public/images";
const FOLDERS = ["logo", "cover", "owner", "team", "store", "visits", "products", "testimonials"] as const;
const WIDTHS = [480, 960, 1600, 2400];
const INPUT = /\.(jpe?g|png|webp|avif|heic|heif|tiff?)$/i;

const WANTED: Record<(typeof FOLDERS)[number], string> = {
  logo: "Profile picture and any logo files",
  cover: "Facebook cover photos",
  owner: "The owner: portraits, press, awards and interviews",
  team: "The team: group portraits and people at work",
  visits: "Guests and creators who visited a branch — each person must agree to appear",
  products: "Product photos: rings, necklaces, bracelets, earrings, bars (plain light background preferred)",
  store: "Shop interiors, storefronts, packaging and live-selling photos",
  testimonials: "Customer screenshots — only with each customer's permission",
};

export interface ProcessedImage {
  id: string;
  folder: string;
  width: number;
  height: number;
  blurDataURL: string;
  sources: { avif: string[]; webp: string[] };
  /** Largest WebP, for <img> fallbacks and OG images. */
  src: string;
}

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

async function processOne(folder: string, file: string): Promise<ProcessedImage> {
  const input = await readFile(path.join(SRC, folder, file));
  // .rotate() with no angle applies EXIF orientation; sharp drops metadata on output by default.
  const base = sharp(input, { failOn: "error" }).rotate();
  const meta = await base.clone().toBuffer({ resolveWithObject: true }).then((r) => r.info);
  const id = `${folder}/${slug(file)}`;
  const outDir = path.join(OUT, folder);
  await mkdir(outDir, { recursive: true });

  const widths = WIDTHS.filter((w) => w < meta.width).concat(meta.width).filter((w, i, a) => a.indexOf(w) === i);
  const sources = { avif: [] as string[], webp: [] as string[] };
  for (const w of widths) {
    const resized = base.clone().resize({ width: w, withoutEnlargement: true });
    const name = `${slug(file)}-${w}`;
    await resized.clone().avif({ quality: 55, effort: 5 }).toFile(path.join(outDir, `${name}.avif`));
    await resized.clone().webp({ quality: 78 }).toFile(path.join(outDir, `${name}.webp`));
    sources.avif.push(`/images/${folder}/${name}.avif ${w}w`);
    sources.webp.push(`/images/${folder}/${name}.webp ${w}w`);
  }

  const blur = await base.clone().resize(16, 16, { fit: "inside" }).webp({ quality: 40 }).toBuffer();
  return {
    id,
    folder,
    width: meta.width,
    height: meta.height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    sources,
    src: `/images/${folder}/${slug(file)}-${widths[widths.length - 1]}.webp`,
  };
}

async function updateTodo(missing: string[]) {
  const file = "TODO.md";
  let text = await readFile(file, "utf8").catch(() => "# TODO\n");
  const start = "<!-- missing-photos:start -->";
  const end = "<!-- missing-photos:end -->";
  const body = missing.length
    ? `### Photos still needed (generated by \`npm run images\`)\n${missing.map((m) => `- [ ] ${m}`).join("\n")}`
    : "### Photos still needed\nAll brand-asset folders have photos. ✓";
  const block = `${start}\n${body}\n${end}`;
  text = text.includes(start) ? text.replace(new RegExp(`${start}[\\s\\S]*?${end}`), block) : `${text.trimEnd()}\n\n${block}\n`;
  await writeFile(file, text);
}

async function main() {
  await rm(OUT, { recursive: true, force: true });
  const images: ProcessedImage[] = [];
  const missing: string[] = [];

  for (const folder of FOLDERS) {
    const files = (await readdir(path.join(SRC, folder)).catch(() => [])).filter((f) => INPUT.test(f)).sort();
    if (files.length === 0) {
      missing.push(`\`brand-assets/${folder}/\` — ${WANTED[folder]}`);
      continue;
    }
    for (const f of files) {
      try {
        images.push(await processOne(folder, f));
        console.log(`✓ ${folder}/${f}`);
      } catch (e) {
        console.warn(`✗ ${folder}/${f}: ${(e as Error).message}`);
      }
    }
  }

  await mkdir("src/content", { recursive: true });
  await writeFile(
    "src/content/images.ts",
    `// Generated by scripts/process-images.ts — do not edit by hand.\n\n` +
      `export interface BrandImage {\n  id: string;\n  folder: string;\n  width: number;\n  height: number;\n  blurDataURL: string;\n  sources: { avif: string[]; webp: string[] };\n  src: string;\n}\n\n` +
      `export const images: readonly BrandImage[] = ${JSON.stringify(images, null, 2)};\n\n` +
      `export function imagesIn(folder: string): readonly BrandImage[] {\n  return images.filter((i) => i.folder === folder);\n}\n`,
  );
  await updateTodo(missing);
  console.log(`${images.length} image(s) processed; ${missing.length} folder(s) still empty (listed in TODO.md).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
