// Generated by scripts/process-images.ts — do not edit by hand.

export interface BrandImage {
  id: string;
  folder: string;
  width: number;
  height: number;
  blurDataURL: string;
  sources: { avif: string[]; webp: string[] };
  src: string;
}

export const images: readonly BrandImage[] = [];

export function imagesIn(folder: string): readonly BrandImage[] {
  return images.filter((i) => i.folder === folder);
}
